[package]
name = "co_managed"
version = "0.1.0"
edition = "2018"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]

[dependencies]
may = "0.3"
parking_lot = "0.12"

[patch.crates-io]
may = { path = "../may" }